name: Update weekly
on:
  schedule:
    - cron: 0 10 * * 1

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: "Update"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Build
        run: |-
          python ./scraper.py
          python ./index.py
      - name: Commit and push if DB changed
        run: |-
          git config --global user.email "catalog-bot@example.com"
          git config --global user.name "catalog-bot"
          git diff --quiet || (git add ./*.json ./index.html && git commit -m "Updated DB")
          git push
