name: Update weekly
on: push
  #schedule:
    #- cron: 0 10 * * 1

jobs:
  deploy:
    name: "Update"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip test
      - name: Build
        run: |-
          ./scraper.py && ./index.py
      - name: Commit and push if DB changed
        run: |-
          git diff
          git config --global user.email "catalog-bot@example.com"
          git config --global user.name "catalog-bot"
          git diff --quiet || (git add ./*.json ./index.html && git commit -m "Updated DB")
          git push
